In [1]:
from ultralytics import YOLO

In [3]:
coco_model = YOLO('yolov8n.pt')

100%|██████████| 6.23M/6.23M [00:21<00:00, 309kB/s]


In [2]:
import os


os.environ["WANDB_DISABLED"] = "true"

In [3]:

# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch

# Use the model
results = model.train(data='data.yaml', epochs=1, verbose = True)  # train the model



New https://pypi.org/project/ultralytics/8.2.2 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.1  Python-3.10.13 torch-2.2.2 CPU (Intel Core(TM) i7-8750H 2.20GHz)
engine\trainer: task=detect, mode=train, model=yolov8n.yaml, data=data.yaml, epochs=1, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train11, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, sa

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.


Freezing layer 'model.22.dfl.conv.weight'


train: Scanning C:\Users\mloet\OneDrive\Desktop\Projects\Traffic_Tracker\datasets\train\labels... 21173 images, 28 backgrounds, 0 corrupt: 100%|██████████| 21173/21173 [00:45<00:00, 460.68it/s]


train: New cache created: C:\Users\mloet\OneDrive\Desktop\Projects\Traffic_Tracker\datasets\train\labels.cache


val: Scanning C:\Users\mloet\OneDrive\Desktop\Projects\Traffic_Tracker\datasets\valid\labels... 2046 images, 3 backgrounds, 0 corrupt: 100%|██████████| 2046/2046 [00:04<00:00, 418.12it/s]


val: New cache created: C:\Users\mloet\OneDrive\Desktop\Projects\Traffic_Tracker\datasets\valid\labels.cache
Plotting labels to runs\detect\train11\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 


c:\Users\mloet\anaconda3\envs\torch10\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\detect\train11
Starting training for 1 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


        1/1         0G      2.094      2.211      2.466         14        640: 100%|██████████| 1324/1324 [2:16:29<00:00,  6.19s/it] 
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 64/64 [05:19<00:00,  5.00s/it]


                   all       2046       2132      0.918      0.767      0.834      0.433

1 epochs completed in 2.365 hours.
Optimizer stripped from runs\detect\train11\weights\last.pt, 6.2MB
Optimizer stripped from runs\detect\train11\weights\best.pt, 6.2MB

Validating runs\detect\train11\weights\best.pt...
Ultralytics YOLOv8.2.1  Python-3.10.13 torch-2.2.2 CPU (Intel Core(TM) i7-8750H 2.20GHz)
YOLOv8n summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 64/64 [04:45<00:00,  4.45s/it]


                   all       2046       2132      0.919      0.767      0.834      0.432
Speed: 2.9ms preprocess, 124.1ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to runs\detect\train11


In [9]:
for i in range(1, 5):
  print(i)

1
2
3
4


In [6]:
import numpy as np
print(np.array([0, 1, 2, 3, 4, 5])+np.array([0, 10, 10, 1, 1]))

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [10]:
import pandas as pd

In [23]:
print(pd.DataFrame({'gs':[1]}).keys())

Index(['gs'], dtype='object')


In [48]:
import ast
from ultralytics import YOLO
import cv2
import util
from sort.sort import *
from util import get_car, read_license_plate, write_csv
import numpy as np
import pandas as pd


In [49]:
def draw_border(img, top_left, bottom_right, color=(0, 255, 0), thickness=10, line_length_x=200, line_length_y=200):
    x1, y1 = top_left
    x2, y2 = bottom_right

    cv2.line(img, (x1, y1), (x1, y1 + line_length_y), color, thickness)  #-- top-left
    cv2.line(img, (x1, y1), (x1 + line_length_x, y1), color, thickness)

    cv2.line(img, (x1, y2), (x1, y2 - line_length_y), color, thickness)  #-- bottom-left
    cv2.line(img, (x1, y2), (x1 + line_length_x, y2), color, thickness)

    cv2.line(img, (x2, y1), (x2 - line_length_x, y1), color, thickness)  #-- top-right
    cv2.line(img, (x2, y1), (x2, y1 + line_length_y), color, thickness)

    cv2.line(img, (x2, y2), (x2, y2 - line_length_y), color, thickness)  #-- bottom-right
    cv2.line(img, (x2, y2), (x2 - line_length_x, y2), color, thickness)

    return img

In [59]:

results = {}

mot_tracker = Sort()

# load models
coco_model = YOLO('./yolov8n.pt')
license_plate_detector = YOLO('./license_plate.pt')

# load video
video_path = 'sample.mp4'
cap = cv2.VideoCapture(video_path)
cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
frame_nmr = 0
# read frames
ret = True

car_dict = {}
while ret:
    ret, frame = cap.read()
    frame_nmr += 1
    if ret:
        detected = {}
        # detect vehicles
        detections = coco_model(frame)[0]
        detections_ = []
        for detection in detections.boxes.data.tolist():
            x1, y1, x2, y2, score, class_id = detection
            if int(class_id) in [2, 3, 5, 7]:
                detections_.append([x1, y1, x2, y2, score])

        # track vehicles
        track_ids = mot_tracker.update(np.asarray(detections_))

        # detect license plates
        license_plates = license_plate_detector(frame)[0]
        for license_plate in license_plates.boxes.data.tolist():
            x1, y1, x2, y2, score, class_id = license_plate

            # assign license plate to car
            xcar1, ycar1, xcar2, ycar2, car_id = get_car(license_plate, track_ids)

            if car_id != -1:

                # crop license plate
                license_plate_crop = frame[int(y1):int(y2), int(x1): int(x2), :]

                # process license plate
                license_plate_crop_gray = cv2.cvtColor(license_plate_crop, cv2.COLOR_BGR2GRAY)
                _, license_plate_crop_thresh = cv2.threshold(license_plate_crop_gray, 64, 255, cv2.THRESH_BINARY_INV)

                # read license plate number
                license_plate_text, license_plate_text_score = read_license_plate(license_plate_crop_thresh)

                if license_plate_text is not None:
                    license_crop_shape = int((x2 - x1) * 400 / (y2 - y1))
                    license_crop = cv2.resize(license_plate_crop, (license_crop_shape, 400)).flatten()

                    detected[car_id] = {'car_id': car_id, 
                          'car_bbox': [xcar1, ycar1, xcar2, ycar2], 
                          'license_plate_bbox': [x1, y1, x2, y2],
                          'license_number': license_plate_text,
                          'license_plate_bbox_score': score,
                          'license_number_score': license_plate_text_score,
                          'license_crop': license_crop,
                          'license_crop_shape': (400, license_crop_shape, 3)
                          }
            

        
        if detected:
          for car in detected:
              # draw car
              car_x1, car_y1, car_x2, car_y2 = detected[car]['car_bbox']
              draw_border(frame, (int(car_x1), int(car_y1)), (int(car_x2), int(car_y2)), (0, 255, 0), 25,
                          line_length_x=200, line_length_y=200)

              # draw license plate
              x1, y1, x2, y2 = detected[car]['license_plate_bbox']
              cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 0, 255), 12)

              # crop license plate
              license_crop = detected[car]['license_crop'].reshape(detected[car]['license_crop_shape'])

              H, W, _ = license_crop.shape

              try:
                  frame[int(car_y1) - H - 100:int(car_y1) - 100,
                        int((car_x2 + car_x1 - W) / 2):int((car_x2 + car_x1 + W) / 2), :] = license_crop

                  frame[int(car_y1) - H - 400:int(car_y1) - H - 100,
                        int((car_x2 + car_x1 - W) / 2):int((car_x2 + car_x1 + W) / 2), :] = (255, 255, 255)

                  (text_width, text_height), _ = cv2.getTextSize(
                      detected[car]['license_number'],
                      cv2.FONT_HERSHEY_SIMPLEX,
                      4.3,
                      17)

                  cv2.putText(frame,
                              detected[car]['license_number'],
                              (int((car_x2 + car_x1 - text_width) / 2), int(car_y1 - H - 250 + (text_height / 2))),
                              cv2.FONT_HERSHEY_SIMPLEX,
                              4.3,
                              (0, 0, 0),
                              17)

              except:
                  pass

        frame = cv2.resize(frame, (1280, 720))

        cv2.imshow('frame', frame)
        key = cv2.waitKey(10)
        if key & 0xFF == ord('q'):
          break

cap.release()



0: 384x640 21 cars, 1 bus, 2 trucks, 112.6ms
Speed: 10.0ms preprocess, 112.6ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 (no detections), 104.5ms
Speed: 2.1ms preprocess, 104.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 23 cars, 1 bus, 2 trucks, 139.4ms
Speed: 3.9ms preprocess, 139.4ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 (no detections), 118.8ms
Speed: 5.0ms preprocess, 118.8ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 22 cars, 1 bus, 2 trucks, 138.1ms
Speed: 6.7ms preprocess, 138.1ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 (no detections), 100.1ms
Speed: 2.0ms preprocess, 100.1ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 23 cars, 1 bus, 2 trucks, 106.2ms
Speed: 2.0ms preprocess, 106.2ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 (no de

In [54]:
for car in detected:
  print(car)

In [58]:
track_ids

array([[     2006.3,       551.8,      2236.2,      752.23,         271],
       [       1251,      905.99,      1656.8,      1065.7,         270],
       [     1274.9,      800.17,      1619.5,      969.41,         266],
       [     1601.3,      584.72,      1871.1,      788.17,         260],
       [     2264.9,       863.1,      2644.3,        1072,         247],
       [     2215.6,      510.44,      2598.1,      875.76,         243],
       [       2090,      835.33,      2401.6,      1135.6,         242],
       [     46.647,      594.04,      248.66,      699.93,         229],
       [     2218.3,      511.19,      2599.6,      876.47,         223],
       [      2.618,      688.36,      230.54,      958.71,         218],
       [     942.76,      594.23,      1040.1,      683.22,         217],
       [     338.38,      586.21,      591.36,       838.2,         209],
       [     1426.7,      639.44,      1754.4,       926.2,         173],
       [     561.91,      582.92,     

In [34]:
license_crop = cv2.resize(license_plate_crop, (int((x2 - x1) * 400 / (y2 - y1)), 400))

In [38]:
license_crop.flatten().reshape((400, 872, 3))

array([[[234, 251, 255],
        [234, 251, 255],
        [235, 251, 255],
        ...,
        [ 55,  45,  46],
        [ 55,  45,  47],
        [ 55,  45,  47]],

       [[234, 251, 255],
        [234, 251, 255],
        [235, 251, 255],
        ...,
        [ 55,  45,  46],
        [ 55,  45,  47],
        [ 55,  45,  47]],

       [[239, 252, 255],
        [239, 252, 255],
        [239, 252, 255],
        ...,
        [ 54,  44,  46],
        [ 55,  45,  47],
        [ 55,  45,  47]],

       ...,

       [[ 64,  51,  46],
        [ 64,  51,  46],
        [ 64,  51,  46],
        ...,
        [ 92,  82,  68],
        [ 90,  80,  66],
        [ 90,  80,  66]],

       [[ 64,  51,  47],
        [ 64,  51,  47],
        [ 64,  51,  47],
        ...,
        [ 91,  81,  67],
        [ 90,  80,  66],
        [ 90,  80,  66]],

       [[ 64,  51,  47],
        [ 64,  51,  47],
        [ 64,  51,  47],
        ...,
        [ 91,  81,  67],
        [ 90,  80,  66],
        [ 90,  80,  66]]

In [47]:
track_ids

array([[       2230,      1079.7,      2683.4,      1357.5,          34],
       [     2340.7,      1778.6,      3370.8,      2147.6,          31],
       [     776.75,      589.74,      969.67,      727.84,          27],
       [     1311.2,      614.67,      1425.8,       686.3,          26],
       [      868.3,      589.02,      975.63,       696.5,          25],
       [     773.93,      586.86,      906.38,      732.61,          22],
       [     2440.3,      590.92,      2626.9,      766.49,          20],
       [     969.63,      625.52,      1091.3,      683.19,          19],
       [     2064.8,      688.34,      2442.7,      898.65,          17],
       [     1454.4,      776.64,      1782.2,        1070,          16],
       [       1389,      667.91,      1681.9,      846.39,          14],
       [     2224.2,      1080.8,      2694.5,      1272.7,          13],
       [     326.52,      528.34,      642.69,      849.93,          12],
       [     2128.8,      452.94,     